/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Archivo;
import static java.awt.SystemColor.info;

/**
 *
 * @author Galindo
 */
public class frmInfo extends javax.swing.JFrame {

    /**
     * Creates new form frmInfo
     */
    public frmInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlinfo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblcantfa = new javax.swing.JLabel();
        lblprom = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        lblpormu = new javax.swing.JLabel();
        lblporfa = new javax.swing.JLabel();
        lblcantmu = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("INFORMACION");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlinfo.setBackground(new java.awt.Color(0, 0, 0));
        pnlinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/evento.jpg"))); // NOI18N
        pnlinfo.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 140));

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estadisticas de Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Total Recaudado :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Porcentaje de personas por Ev. Familiar :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Cantidad de personas por Ev. Familiar :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Promedio venta de Boletas:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Cantidad de personas por Ev. Musical :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Porcentaje de personas por Ev. Musical :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lblcantfa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblcantfa.setForeground(new java.awt.Color(255, 0, 0));
        lblcantfa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcantfa.setText("0");
        jPanel1.add(lblcantfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 80, -1));

        lblprom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblprom.setForeground(new java.awt.Color(255, 0, 0));
        lblprom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblprom.setText("0");
        jPanel1.add(lblprom, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 80, -1));

        lbltotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbltotal.setForeground(new java.awt.Color(255, 0, 0));
        lbltotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltotal.setText("0");
        jPanel1.add(lbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 80, -1));

        lblpormu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblpormu.setForeground(new java.awt.Color(255, 0, 0));
        lblpormu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpormu.setText("0");
        jPanel1.add(lblpormu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 80, -1));

        lblporfa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblporfa.setForeground(new java.awt.Color(255, 0, 0));
        lblporfa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblporfa.setText("0");
        jPanel1.add(lblporfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 80, -1));

        lblcantmu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblcantmu.setForeground(new java.awt.Color(255, 0, 0));
        lblcantmu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcantmu.setText("0");
        jPanel1.add(lblcantmu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 80, -1));

        btnRegresar.setBackground(new java.awt.Color(51, 0, 0));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        btnRegresar.setToolTipText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        btnRegresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRegresarKeyPressed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 60, 60));

        jButton1.setBackground(new java.awt.Color(51, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calcular.png"))); // NOI18N
        jButton1.setToolTipText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 60, 60));

        pnlinfo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 500, 350));

        getContentPane().add(pnlinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        frmPrincipal ppal=new frmPrincipal();
        ppal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRegresarKeyPressed
        frmPrincipal ppal=new frmPrincipal();
        ppal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Archivo archivo = new Archivo();
    
    // Llamar al método calcularMetricas y pasarle la instancia actual de frmInfo
    archivo.calcularMetricas(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    public javax.swing.JLabel lblcantfa;
    public javax.swing.JLabel lblcantmu;
    public javax.swing.JLabel lblporfa;
    public javax.swing.JLabel lblpormu;
    public javax.swing.JLabel lblprom;
    public javax.swing.JLabel lbltotal;
    private javax.swing.JPanel pnlinfo;
    // End of variables declaration//GEN-END:variables
}
