/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Archivo;
import java.awt.Image;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Galindo
 */
public class frmVenta extends javax.swing.JFrame {

    /**
     * Creates new form frmVenta
     */
    public frmVenta() {
        initComponents();
        ImageIcon imagen=new ImageIcon("src/imagenes/evento.jpg");
        Icon icono=new ImageIcon(imagen.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_DEFAULT));
        lblLogo.setIcon(icono);
        this.repaint();
    }
    
    ArrayList<String> listado=new ArrayList();
    DefaultListModel modeloL=new DefaultListModel();
     double Total;
    double precioBase = 0;
     double valorTotal;
     Archivo com= new  Archivo();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void buscar(String cod){
        Archivo archivo=new Archivo();
        archivo.buscarEve(cod);
        if(archivo.getEncontro()){
            lblNom.setText(archivo.getNombre());
            lblTipo.setText(archivo.getTipoB());
            
        }
    
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlventa = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnlisteve = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("VENTAS LA COQUETA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlventa.setBackground(new java.awt.Color(0, 0, 0));
        pnlventa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/evento.jpg"))); // NOI18N
        pnlventa.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 130));

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Venta de Boleteria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValor.setBackground(new java.awt.Color(204, 0, 0));
        lblValor.setForeground(new java.awt.Color(255, 0, 0));
        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValor.setText("0");
        jPanel1.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 130, 20));

        lblTipo.setBackground(new java.awt.Color(204, 0, 0));
        lblTipo.setForeground(new java.awt.Color(255, 0, 0));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("-");
        jPanel1.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 130, 20));

        lblPrecio.setBackground(new java.awt.Color(204, 0, 0));
        lblPrecio.setForeground(new java.awt.Color(255, 0, 0));
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("0");
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 130, 20));

        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodKeyTyped(evt);
            }
        });
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 80, -1));

        jLabel7.setBackground(new java.awt.Color(204, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Tipo de Boleta :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Valor a Pagar :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        jLabel6.setBackground(new java.awt.Color(204, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Precio de la Boleta :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setBackground(new java.awt.Color(204, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Cantidad :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel4.setBackground(new java.awt.Color(204, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Nombre del evento :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblNom.setBackground(new java.awt.Color(204, 0, 0));
        lblNom.setForeground(new java.awt.Color(255, 0, 0));
        lblNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNom.setText("-");
        jPanel1.add(lblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 130, 20));

        txtCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantActionPerformed(evt);
            }
        });
        txtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantKeyTyped(evt);
            }
        });
        jPanel1.add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 100, -1));

        btnAgregar.setBackground(new java.awt.Color(51, 0, 0));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnAgregar.setToolTipText("Comprar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        btnAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAgregarKeyPressed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 60, 60));

        btnlisteve.setBackground(new java.awt.Color(51, 0, 0));
        btnlisteve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listadoeventos.png"))); // NOI18N
        btnlisteve.setToolTipText("Lista de eventos");
        btnlisteve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlisteveActionPerformed(evt);
            }
        });
        jPanel1.add(btnlisteve, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 60, 60));

        btnRegresar.setBackground(new java.awt.Color(51, 0, 0));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        btnRegresar.setToolTipText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        btnRegresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRegresarKeyPressed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 60, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Codigo :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        pnlventa.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 520, 330));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Fecha :");
        pnlventa.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 0, 0));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("-");
        pnlventa.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 80, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Hora :");
        pnlventa.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        lblHora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 0, 0));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("-");
        pnlventa.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 80, -1));

        getContentPane().add(pnlventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       //darle forma a la fecha y la hora
        DateFormat hora=new SimpleDateFormat("HH:mm:ss");
        DateFormat fecha=new SimpleDateFormat("dd/MM/yyyy");
        Date date=new Date();//traer la fecha y hora del sistema
        lblFecha.setText(fecha.format(date));
        lblHora.setText(hora.format(date));
    }//GEN-LAST:event_formWindowActivated

    private void btnlisteveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlisteveActionPerformed
        frmListadoV eve=new frmListadoV();
        eve.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnlisteveActionPerformed

    private void btnAgregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAgregarKeyPressed
        listado.add(lblNom.getText() + " || " + lblTipo.getText()+" || "+txtCant.getText()+" || "+lblPrecio.getText()+" || "+lblValor.getText());

    }//GEN-LAST:event_btnAgregarKeyPressed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        Archivo archivo = new Archivo();
        
        // Obtener el tipo de boleta y la cantidad
        String tipoBoleta = lblTipo.getText(); // "Familiar" o "Musical"
        int cantidad = Integer.parseInt(txtCant.getText());
        
        // Precios base según el tipo de boleta
        if (tipoBoleta.equalsIgnoreCase("Familiar nocturno")) {
            precioBase = 8000 * 1.15;
            
            //info.lblcantfa.setText(String.valueOf(archivo.getCantfa()));
        } else if (tipoBoleta.equalsIgnoreCase("Musical nocturno")) {
            precioBase = 12500 * 1.25; // Precio base para boletas musicales
            
        } else if (tipoBoleta.equalsIgnoreCase("Musical")) {
            precioBase = 12500;
            
        } else if (tipoBoleta.equalsIgnoreCase("Familiar")) {
            precioBase = 8000;
            
        }else{
            JOptionPane.showMessageDialog(null,"ERROR: ");
        
        }

        com.setCodigo(txtCod.getText());
        com.setNombre(lblNom.getText());
        com.setTipoB(lblTipo.getText());
        com.setCantidad(txtCant.getText());
        com.setPrecioU(lblPrecio.getText());
        com.setValorCom(lblValor.getText());

        
        valorTotal = precioBase * cantidad;
        Total = Total + valorTotal; // Sumar al total general
        
        lblPrecio.setText(String.valueOf(precioBase));
        lblValor.setText(String.valueOf(valorTotal));

        archivo.escribir(
            txtCod.getText(),
            lblNom.getText(),
            lblTipo.getText(),
            txtCant.getText(),
            lblPrecio.getText(),
            lblValor.getText()
        );
        
        String boletaInfo = lblNom.getText() + " || " + lblTipo.getText() + " || " +
        txtCant.getText() + " || " + lblPrecio.getText() + " || " +
        lblValor.getText();
        modeloL.addElement(boletaInfo);
       
        // Limpiar los campos para una nueva compra
        txtCod.setText("");
        txtCant.setText("");
        lblNom.setText("");
        lblTipo.setText("");
        lblPrecio.setText("0");
        lblValor.setText("0");
        
        txtCod.requestFocus();
        

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKeyTyped
        //validacion solo numeros
        int tecla=evt.getKeyChar();
        boolean numeros=tecla>=48 && tecla<=57;
        if(!numeros){
            evt.consume();

        }
        //limitar la cantidad de digitos en la caja de texto
        if(txtCant.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_txtCantKeyTyped

    private void txtCantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKeyPressed

    }//GEN-LAST:event_txtCantKeyPressed

    private void txtCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantActionPerformed

    }//GEN-LAST:event_txtCantActionPerformed

    private void txtCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyTyped
        //validacion solo numeros
        int tecla=evt.getKeyChar();
        boolean numeros=tecla>=48 && tecla<=57;
        if(!numeros){
            evt.consume();

        }
        //limitar la cantidad de digitos en la caja de texto
        if(txtCod.getText().length()>=4){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodKeyTyped

    private void txtCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyPressed
        boolean encontro=false;
        if(evt.getKeyCode()==evt.VK_ENTER){
            buscar(txtCod.getText());
            txtCant.requestFocus();
            txtCant.selectAll();
        }
    }//GEN-LAST:event_txtCodKeyPressed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void btnRegresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRegresarKeyPressed
        frmPrincipal ppal=new frmPrincipal();
        ppal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarKeyPressed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        frmPrincipal ppal=new frmPrincipal();
        ppal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnlisteve;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlventa;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCod;
    // End of variables declaration//GEN-END:variables
}
